Classes/Aggregate/AbstractOverridesAggregate.php, Classes/Aggregate/ContentRenderingAggregate.php, Classes/Aggregate/SqlAwareTrait.php, Classes/Aggregate/TcaAggregate.php, Classes/Aggregate/TcaAwareTrait.php, Classes/Aggregate/TtContentOverridesAggregate.php, Classes/CodeGenerator/HtmlCodeGenerator.php, Classes/Controller/ExportController.php
=> Inline handling

Classes/Aggregate/AbstractOverridesAggregate.php
=> [BUGFIX] Re-add generation of locallang_db labels

Classes/Aggregate/TtContentOverridesAggregate.php
=> [FEATURE] Add CType separator for extension types

Classes/Aggregate/AbstractOverridesAggregate.php, Classes/Aggregate/TtContentOverridesAggregate.php, Classes/FileCollection/AbstractFileCollection.php, Classes/FileCollection/LanguageFileCollection.php, Classes/FileCollection/PhpFileCollection.php, Classes/FileCollection/PlainTextFileCollection.php, Classes/FileCollection/SqlFileCollection.php
=> Restore file generation

Classes/FileCollection/PhpFileCollection.php
=> [BUGFIX] Follow up for 6d3262f to append PHP files correctly

Classes/Aggregate/TcaAwareTrait.php
=> [BUGFIX] Prefer SQL field definitions from current table

Classes/Controller/ExportController.php
=> [BUGFIX] Reorder extension key replacement

Classes/Aggregate/ContentRenderingAggregate.php
=> [BUGFIX] Add sorting for inline elements in DatabaseQueryProcessor

Classes/Aggregate/InlineContentColPosAggregate.php, Classes/Aggregate/TtContentOverridesAggregate.php, Classes/Controller/ExportController.php
=> Nested content colpos

Classes/CodeGenerator/HtmlCodeGenerator.php
=> [BUGFIX] Enforce table in <f:cObject> to ensure correct FileProcessing

Classes/Aggregate/AbstractOverridesAggregate.php, Classes/Aggregate/BackendPreviewAggregate.php, Classes/Aggregate/TcaAggregate.php, Classes/Aggregate/TcaAwareTrait.php, Classes/CodeGenerator/BackendFluidCodeGenerator.php, Classes/Controller/ExportController.php, Resources/Private/Language/locallang.xlf, ext_conf_template.txt
=> Add backend preview template

Classes/Controller/ExportController.php, Resources/Private/Backend/Templates/Export/List.html
=> [FEATURE] Store extension key in backend user settings

Classes/Aggregate/BackendPreviewAggregate.php, Classes/Aggregate/ContentRenderingAggregate.php
=> [TASK] Ensure correct Fluid paths for content element rendering

Classes/Aggregate/BackendPreviewAggregate.php
=> [BUGFIX] Correct backend preview template paths

.travis.yml, Classes/Aggregate/ContentRenderingAggregate.php, composer.json
Also execute phpstan code analysis on PHP 7.0 Travic CI builds.
=> [FEATURE] Add phpstan/phpstan as dev requirement

.travis.yml
This helps to speed up Travis CI builds and ensures they can be cached on
success.
=> [TASK] Improve build matrix and skip superfluous steps

Tests/Functional/Controller/AbstractExportControllerTestCase.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php, Tests/Functional/Controller/Ressources/ExportControllerTest.php, Tests/Functional/Controller/TypoScript/ExportControllerTest.php
Tests are split by a testing group. This should help understanding their
purpose and to be able to add new tests in a clear structure.
=> [TASK] Split functional tests

Classes/Aggregate/BackendPreviewAggregate.php, Tests/Functional/Controller/AbstractExportControllerTestCase.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php, Tests/Functional/Controller/TypoScript/ExportControllerTest.php, Tests/Functional/Fixtures/Database/pages.xml, Tests/Functional/Fixtures/Database/sys_file.xml, Tests/Functional/Fixtures/Database/tt_content.xml, Tests/Functional/Fixtures/mask.json
=> Fix backend preview data aggregation

Classes/Aggregate/ContentRenderingAggregate.php
=> Improve CType handling in DatabaseQueryProcessor

Classes/Aggregate/ContentElementIconAggregate.php, Classes/Aggregate/NewContentElementWizardAggregate.php, Classes/Aggregate/TtContentOverridesAggregate.php, Classes/Controller/ExportController.php, Tests/Functional/Controller/Ressources/ExportControllerTest.php, Tests/Functional/Fixtures/mask.json
=> Fix content element icons

Classes/Aggregate/BackendPreviewAggregate.php, Classes/Aggregate/ContentRenderingAggregate.php, Classes/CodeGenerator/HtmlCodeGenerator.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php, Tests/Functional/Fixtures/mask.json
=> Fix handling of empty content elements

Classes/Aggregate/TcaAggregate.php
=> Use correct SQL for timestamp fields in new tables

.travis.yml
Currently there are problems using Composer with Travis CI trusty
distribution.
See https://github.com/travis-ci/travis-ci/issues/8113
=> [TASK] Downgrade Travis CI dist

Classes/CodeGenerator/BackendFluidCodeGenerator.php
=> [BUGFIX] Generate correct Fluid template code for sys_file_reference

Classes/Aggregate/ExtensionConfigurationAggregate.php, Classes/Aggregate/TtContentOverridesAggregate.php, Tests/Functional/Controller/Configuration/ExportControllerTest.php
=> Reformat extemconf

Classes/Aggregate/AbstractOverridesAggregate.php, Classes/Aggregate/BackendPreviewAggregate.php, Classes/Aggregate/TcaAggregate.php, Classes/Aggregate/TcaAwareTrait.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php, Tests/Functional/Controller/Ressources/ExportControllerTest.php
=> [FEATURE] Move items labels to locallang_db.xlf

Classes/Aggregate/ContentElementIconAggregate.php, Tests/Functional/Controller/Ressources/ExportControllerTest.php
This patch adds proper TCA typeicon_classes definition for content
elements.
=> [FEATURE] Extend typeicon_classes for content elements

Classes/Controller/ExportController.php, Resources/Private/Backend/Templates/Export/List.html, Tests/Functional/Controller/AbstractExportControllerTestCase.php, ext_tables.php
=> [FEATURE] Save extension key for every action

Classes/Aggregate/ExtensionConfigurationAggregate.php, Classes/Controller/ExportController.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php, Tests/Functional/Controller/Configuration/ExportControllerTest.php
This also sets psr-4 autoload information for an export.
Resolves: #117 
Resolves: #119
=> [FEATURE] Export composer.json

Classes/Aggregate/ContentElementIconAggregate.php
Instead of only looking for png files, now
also svg files are respected.
=> [FEATURE] Allow providing SVG icon files

Classes/Aggregate/BackendPreviewAggregate.php, Tests/Functional/Controller/BackendPreview/ExportControllerTest.php
This patch allows to set a backend template path for all content
elements instead of the need to configure each element separately.
=> Simplify backend preview configuration

Classes/Aggregate/AbstractInlineContentAggregate.php, Classes/Aggregate/InlineContentCTypeAggregate.php, Classes/Aggregate/InlineContentColPosAggregate.php, Tests/Functional/Controller/DataProvider/ExportControllerTest.php, Tests/Functional/Fixtures/Configuration/mask-default.json, Tests/Functional/Fixtures/Database/tt_content.xml, Tests/Functional/Fixtures/Database/tx_maskexampleexport_additionalcontent.xml
=> Fix multi-nested content elements

Classes/Aggregate/BackendPreviewAggregate.php, Tests/Functional/Fixtures/Configuration/mask-default.json
=> Correctly resolve backend template path with underscore

Classes/CodeGenerator/HtmlCodeGenerator.php
- Usage of fieldType enumerations
- New fields like palettes, groups and timestamps are considered
=> [TASK] Update HtmlCodeGenerator for mask version 6

Classes/CodeGenerator/BackendFluidCodeGenerator.php
EXT:lang must be changed to EXT:core as this system extension doesn't exist anymore
=> [BUGFIX] Update path to language file

.travis.yml, Classes/Aggregate/AbstractAggregate.php, Classes/Controller/ExportController.php, Tests/Functional/Controller/AbstractExportControllerTestCase.php, Tests/Functional/Controller/Ressources/ExportControllerTest.php, Tests/Functional/Fixtures/Configuration/mask-default.json, Tests/Functional/Fixtures/Configuration/mask-empty-columns.json, composer.json, ext_emconf.php, sonar-project.properties
This patch ensures compatibility to mask 7.1 and its new code architecture.
Resolves: #179
=> [FEATURE] Add support for mask 7.1
